type Boots {
    id: ID!
    product_id: Int!
    product_name: String!
    male: Boolean!
    female: Boolean!
    child: Boolean!
    sizes: [Float!]!
    colors: [String!]!
    price: Int!
}

type Query {
    allBoots: [Boots!]!
    getBoot(product_id: Int!): Boots
    getBootsBySize(size: Float!): [Boots]
    getBootsByColor(color: String!): [Boots]
}
