enum FootwearSubCategory {
    CASUAL
    SNEAKERS
    BOOTS
    DRESS_SHOE
}

type Footwear {
    id: ID!
    product_id: Int!
    product_name: String!
    sub_category: FootwearSubCategory!
}

type Query {
    allFootwearBySubCategory(sub_category: FootwearSubCategory!): [Footwear]
    getFootwearByProductID(product_id: Int!): Footwear
}
