enum ProductCategory {
    FOOTWEAR
    TOPS
    BOTTOMS
    OUTERWEAR
    ACCESSORY
}

type Product {
    id: ID!
    product_name: String!
    category: ProductCategory!
}

type Query {
    allProducts: [Product!]
    productsByCategory(category: ProductCategory!): [Product!]
}

type Mutation {
    removeProduct(product_id: Int!): Boolean!
    updateProductName(product_id: Int!, product_name: String!): Boolean!
    updatePrice(product_id: Int!, price: Float!): Boolean!
    updateProductColor(product_id: Int!, colors: [String!]!): Boolean!
    updateProductSize(product_id: Int!, sizes: [String!]!): Boolean!
}