enum ProductCategory {
    FOOTWEAR
    TOPS
    BOTTOMS
    OUTERWEAR
    ACCESSORY
}

type Product {
    id: ID!
    product_name: String!
    category: ProductCategory!
}

type Query {
    allProducts: [Product!]
    productsByCategory(category: ProductCategory!): [Product!]
}

type Mutation {
    removeProduct(product_id: Int!): Boolean!
    updateProductName(product_id: Int!, product_name: String!): Boolean!
    addFootwearProduct(
    product_name: String! 
    sub_category: FootwearSubCategory,
    male: Boolean!,
    female: Boolean!,
    child: Boolean!,
    sizes: [Float!]!,
    colors: [String!]!,
    price: Float!
    ): Boolean!
    updatePrice(price: Int!): Boolean!
    updateProductColor(colors: [String!]!): Boolean!
    updateProductSize(sizes: [String!]!): Boolean!
}